### ISSUE TITLE
More "mutating arrays is not supported"

### ISSUE THREAD

**Issue by sevenfourtwo** [FluxML/GeometricFlux.jl#103]
Great work on this package! Really like it.

While using it I ran in two cases where I got the "mutating arrays is not supported" error, both when using FeaturedGraphs. The following minimal code triggers the error:

```
using LightGraphs, Flux, GeometricFlux, GraphSignals

graph = SimpleGraph(10,10)
node_features = zeros(Float32, 4, 10)

featured_graph = GeometricFlux.FeaturedGraph(graph, node_features)

model = Chain(
  GCNConv(4=>4, relu),
  node_feature,
  Dense(4, 1)
)

grad = Flux.gradient(params(model)) do
  sum(model(featured_graph))
end
```

The first errors is caused by the code [here](https://github.com/yuehhua/GeometricFlux.jl/blob/be2c2b887172f1fe0be2e111103344c76a3b5a32/src/layers/conv.jl#L47) and can be solved by changing the creation of the FeaturedGraph to the code below. Maybe there should be an earlier check to ensure the types are the same (with a more meaningful error message)?

```
adj_matrix = Matrix{Float32}(adjacency_matrix(graph))
featured_graph = GeometricFlux.FeaturedGraph(adj_matrix, node_features)
```

The second error is caused on [this line](https://github.com/yuehhua/GeometricFlux.jl/blob/be2c2b887172f1fe0be2e111103344c76a3b5a32/src/layers/conv.jl#L60) and can be solved by disabling the cache on the GCNConv layer. It seems zygote is complaining about the `g.fg.graph = A` part in the code, which is skipped when the cache is disabled. I'm not even sure caching like this is possible in code that will be differentiated.

Full working code:

```
using LightGraphs, Flux, GeometricFlux, GraphSignals

graph = SimpleGraph(10,10)
node_features = zeros(Float32, 4, 10)

adj_matrix = Matrix{Float32}(adjacency_matrix(graph))     # ADDED
featured_graph = GeometricFlux.FeaturedGraph(adj_matrix, node_features)     # CHANGED

model = Chain(
  GCNConv(4=>4, relu, cache=false),     # CHANGED
  node_feature,
  Dense(4, 1)
)

grad = Flux.gradient(params(model)) do
  sum(model(featured_graph))
end
```

package versions used:

```
  [587475ba] Flux v0.11.1
  [7e08b658] GeometricFlux v0.7.1 `https://github.com/yuehhua/GeometricFlux.jl.git#master`
  [3ebe565e] GraphSignals v0.1.1
  [093fc24a] LightGraphs v1.3.3
  [e88e6eb3] Zygote v0.5.8
```

**Comment by yuehhua** [comment]
Thank you for your suggestions and pointing out the lack of documentation. The `cache` argument is designed for input of `FeaturedGraph`. However, this argument is currently taken off and an alternative mechanism is designed. Thank you for this issue.
