### ISSUE TITLE
GAT example not working

### ISSUE THREAD

**Issue by alperyilmaz** [FluxML/GeometricFlux.jl#135]
I changed the preprocessing part 
```
train_X = Float32.(features) |> gpu  # dim: num_features * num_nodes
train_y = Float32.(labels) |> gpu  # dim: target_catg * num_nodes
```
into
```
train_X = Matrix{Float32}(features) |> gpu  # dim: num_features * num_nodes
train_y = Matrix{Float32}(labels) |> gpu  # dim: target_catg * num_nodes
```
in order to avoid some GPU errors. However, the training function is stuck at epoch 1 even after many minutes.

`model(train_X)` gives 56×1 array, but `train_y` is 7×2708 array.  Is there a problem with data dimension or reshaping?

thanks.

**Comment by yuehhua** [comment]
Computing gradient for the whole graph could take longer time. It is suggested to compute less than 64 nodes for gradient for each updates. A proper node number to update would be 32. I will release a new feature for node sampling to act like batch size in classical deep learning model. It will update gradient for some nodes in a graph randomly.

**Comment by yuehhua** [comment]
Check new version [here](https://github.com/FluxML/GeometricFlux.jl/blob/master/examples/gat.jl). If you have any questions, it's welcome to reopen the issue.
