### ISSUE TITLE
drop ScatterNNlib in favor of NNlib.scatter

### ISSUE THREAD

**Issue by CarloLucibello** [FluxML/GeometricFlux.jl#191]
I see no issue for this, so better create one to track progress. 

@yuehhua did you compare the performance of the two implementations?

**Comment by CarloLucibello** [comment]
Fixed by #187?

**Comment by yuehhua** [comment]
@CarloLucibello I haven't benchmark them. The use of NNlib.scatter should work in master branch. I correct the arguments in #187. However, due to deps update and introduction of new features, #187 also makes new issues #194 and #195.
