### ISSUE TITLE
drop support in layer for arbitrary graph types and use only FeaturedGraphs

### ISSUE THREAD

**Issue by CarloLucibello** [FluxML/GeometricFlux.jl#201]
Currently, layer constructors support adjacency matrices, adj lists, lightgraphs's graphs, metagraphs, abstract graphs ...
and this produces a lot of boilerplate code and sometimes performance problems. Moreover, there is little transparency about the conversions going on internally.

Since it is quite easy to create a FeaturedGraph from any other graph type, let's have the users transparently do that, 
so that the gnn layers have to interact only with a single graph type fully under our control.

**Comment by yuehhua** [comment]
Dropping support for arbitrary graph types in layer constructors is fine to me.

In the original design, I would like to avoid redundant computation of the same graph structure. Keep the graph structure static in layer can save some effort for converting graph formats and calculation of Laplacian matrix.
