### ISSUE TITLE
Stable docs 404 in README

### ISSUE THREAD

**Issue by logankilpatrick** [FluxML/GeometricFlux.jl#221]
https://fluxml.ai/GeometricFlux.jl/stable

**Comment by logankilpatrick** [comment]
Opened: https://github.com/JuliaDocs/Documenter.jl/issues/1674

**Comment by logankilpatrick** [comment]
@yuehhua can we try tagging a new release ?

**Comment by yuehhua** [comment]
Let me check current state and then I will tag new release.

**Comment by logankilpatrick** [comment]
Great! Thank you. Just trying to do some cleanup this weekend :)

**Comment by yuehhua** [comment]
Thank you so much. I just fire a new release. Let's see if stable doc works.

**Comment by logankilpatrick** [comment]
Fixed! Thank you.
