### ISSUE TITLE
gradient for GATConv layer is very slow

### ISSUE THREAD

**Issue by afternone** [FluxML/GeometricFlux.jl#243]
```julia
@show gradient(X -> loss(X, train_y), train_X) # line 45 in 'example/gat.jl'
```
This line takes more than 200s on CPU, but the forward pass takes less than 1s on the same CPU.

**Comment by yuehhua** [comment]
Computing gradient for the whole graph could take longer time. It is suggested to compute less than 64 nodes for gradient for each updates. A proper node number to update would be 32. I will release a new feature for node sampling to act like batch size in classical deep learning model. It will update gradient for some nodes in a graph randomly.

**Comment by yuehhua** [comment]
Check new version [here](https://github.com/FluxML/GeometricFlux.jl/blob/master/examples/gat.jl). If you have any questions, it's welcome to reopen the issue.
