### ISSUE TITLE
examples/gcn.jl doesn't work

### ISSUE THREAD

**Issue by jarbus** [FluxML/GeometricFlux.jl#245]
I get the following error when running on CPU (and similar error when on GPU) when running `examples/gcn.jl`.

```
ERROR: LoadError: MethodError: no method matching GCNConv(::Matrix{Float32}, ::Pair{Int64, Int64}, ::typeof(relu))
Closest candidates are:
  GCNConv(::A, ::B, ::F, ::S) where {A<:(AbstractMatrix{T} where T), B, F, S<:AbstractFeaturedGraph} at /home/jack/.julia/packages/GeometricFlux/ErNzP/src/layers/conv.jl:20
  GCNConv(::AbstractFeaturedGraph, ::Pair{Int64, Int64}, ::Any; init, bias) at /home/jack/.julia/packages/GeometricFlux/ErNzP/src/layers/conv.jl:26
  GCNConv(::Pair{Int64, Int64}, ::Any; kwargs...) at /home/jack/.julia/packages/GeometricFlux/ErNzP/src/layers/conv.jl:34
```

**Comment by ndgnuh** [comment]
> I think
> 
> ```julia
> fg = FeaturedGraph(g) |> gpu
> ```
> 
> should be fine.


After using this, I got 
```
LoadError: MethodError: no method matching zero(::Type{Any})
```

Top level stack trace points to
```
 [41] macro expansion
    @ ~/.cache/julia/packages/Flux/qp1gc/src/optimise/train.jl:136 [inlined] 
 [42] top-level scope
    @ ~/.cache/julia/packages/Juno/n6wyj/src/progress.jl:134
```
I don't even use Juno.

**Comment by zqni** [comment]
> ```julia
> fg = FeaturedGraph(g) |> gpu
> ```

Got different waring but I think it's similar due to type error.
```
GPU broadcast resulted in non-concrete element type Any.
```
And all examples met with the same issue mentioned here.

**Comment by zqni** [comment]
> 

I believe this error is related to the Zygote which might result from the wrong setting somewhere and I could run the code in CPU perfectly.

**Comment by zqni** [comment]
> > I think
> > ```julia
> > fg = FeaturedGraph(g) |> gpu
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > should be fine.
> 
> After using this, I got
> 
> ```
> LoadError: MethodError: no method matching zero(::Type{Any})
> ```
> 
> Top level stack trace points to
> 
> ```
>  [41] macro expansion
>     @ ~/.cache/julia/packages/Flux/qp1gc/src/optimise/train.jl:136 [inlined] 
>  [42] top-level scope
>     @ ~/.cache/julia/packages/Juno/n6wyj/src/progress.jl:134
> ```
> 
> I don't even use Juno.

I believe this error is related to the Zygote which might result from the wrong setting somewhere and I could run the code in CPU perfectly.

**Comment by zqni** [comment]
> > I think
> > ```julia
> > fg = FeaturedGraph(g) |> gpu
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > should be fine.
> 
> After using this, I got
> 
> ```
> LoadError: MethodError: no method matching zero(::Type{Any})
> ```
> 

I believe this error is related to the Zygote which might result from the wrong setting somewhere and I could run the code in CPU perfectly.

**Comment by yuehhua** [comment]
I have updated the master branch and it works with following:

```julia
fg = FeaturedGraph(g)  # pass to gpu together in model layers

## Model
model = Chain(GCNConv(fg, num_features=>hidden, relu),
              Dropout(0.5),
              GCNConv(fg, hidden=>target_catg),
              ) |> gpu;
```

But there is a bit problem. The loss doesn't drop but increase. I'm still fixing this.
