### ISSUE TITLE
How do you use `bypass_graph` with a `Flux.Chain`?

### ISSUE THREAD

**Issue by emsal0** [FluxML/GeometricFlux.jl#248]
https://github.com/FluxML/GeometricFlux.jl/blob/c8396e4a34637c06c5c479851877c44e1a85a530/src/layers/misc.jl#L6-L13

Say I want to use a `Flux.Chain` to apply a neural network to each node feature vector. I don't think I can just pass in the `Chain` here, because it will be applied to the whole node feature matrix, which a) doesn't separate the node features and b) might be of variable size. Should the functionality of `bypass_graph` be changed so that it applies a mapping over node feature vectors instead?

**Comment by yuehhua** [comment]
The `bypass_graph` is designed to pass node/edge/global features over distinct networks. You want to pass each node features over a neural network. I am curious what is the difference between passing node features one by one and passing whole node features as a matrix? Computationally, it should be the same and we don't need to separate node features for that.

**Comment by yuehhua** [comment]
In the latest version, `bypass_graph` has been deprecated. The functionality is replaced by `GraphParallel` layer.
