### ISSUE TITLE
Compatibility with `GraphSignals.jl` Check 

### ISSUE THREAD

**Issue by axla-code** [FluxML/GeometricFlux.jl#263]
Hi @yuehhua !
[The change ](https://github.com/yuehhua/GraphSignals.jl/blob/8581a731506a7a0beda2842f9d50b3c29100b0e6/CHANGELOG.md#031) of `check_num_node` to `check_num_nodes` in `GraphSignals.jl` breaks the code for evaluating a graph model based on a feature graph.

## MWE
```julia
using Flux
using GraphSignals
using GeometricFlux
using LinearAlgebra
using LightGraphs.SimpleGraphs

# Initialize variables
num_node = 3
num_features = 2
hidden = 16

# Preprocess data
train_X = Matrix{Float32}(rand(num_features, num_node))

# Create featured graph
adj = [1 1 0;
        1 1 1;
        0 1 1]
fg = FeaturedGraph(adj)

# Define GCN model
model = Chain(GCNConv(fg, num_features=>hidden, relu),
              GCNConv(fg, hidden=>num_features),
              )

print(model(train_X))

```

## Error message
Running this code gives the error message:

```julia
ERROR: LoadError: UndefVarError: check_num_node not defined
```

NB that instead of ` using Graphs.SimpleGraphs`  I use `using LightGraphs.SimpleGraphs` as there is some compatibility issues, see my reply in #262

**Comment by yuehhua** [comment]
OK, it's my miss. Thank you for reporting this.

**Comment by yuehhua** [comment]
@axla-code Would you please mention your GeometricFlux and GraphSignals version?

**Comment by axla-code** [comment]
Hi @yuehhua I realized that I had the same problem as @arnaudmgh in #262 
Updating Julia from `1.5` to `1.7` solves the issue.
