### ISSUE TITLE
examples/gde.jl not working

### ISSUE THREAD

**Issue by gcrth** [FluxML/GeometricFlux.jl#264]
The example in <https://github.com/FluxML/GeometricFlux.jl/blob/master/examples/gde.jl> can not run. There will be an error when running the last line of code, and the error is shown below.

```
julia> @epochs epochs Flux.train!(loss, ps, train_data, opt, cb=throttle(evalcb, 10))
[ Info: Epoch 1
┌ Warning: Expected 7344092 params, got 272
└ @ Flux ~/.julia/packages/Flux/BPPNj/src/utils.jl:647
ERROR: LoadError: DimensionMismatch("array could not be broadcast to match destination")
```
 
I cannot find any solution for solving this, and I wonder if there is any suggestion for fixing this.

Any help is appreciated, thank you.

**Comment by yuehhua** [comment]
Yeah, it comes from broken `GCNConv` layer. I will got it fixed soon.
