### ISSUE TITLE
Failure as `NNlib.within_grad` is deleted

### ISSUE THREAD

**Issue by mcabbott** [FluxML/GeometricFlux.jl#349]
Flux's downstream tests see a failure with latest NNlib, because this line calls a function which no longer exists:

https://github.com/FluxML/GeometricFlux.jl/blob/c306989f3aeb25d41e0fe00858880caf56d1e3f5/src/operation.jl#L46

Removed in https://github.com/FluxML/NNlib.jl/pull/434. One path would be just to upgrade here. Another would be to make an NNlib PR adding a deprecation for the removed function (which was assumed to be internal); this option would keep old versions of this package working with new NNlib.

**Comment by yuehhua** [comment]
@mcabbott Thank you so much for raising this issue!
