### ISSUE TITLE
GAT example fails

### ISSUE THREAD

**Issue by hexiang2019** [FluxML/GeometricFlux.jl#43]
Hi!

Thank you for your GeometricFlux.

I was trying your example codes for GAT but failed.

_ERROR: LoadError: MethodError: no method matching adjlist(::SimpleGraph{Int64})
Closest candidates are:
  adjlist(!Matched::T) where T<:MessagePassing at /home/xh/.julia/packages/GeometricFlux/u3Wfx/src/layers/msgpass.jl:5
  adjlist(!Matched::T) where T<:GeometricFlux.Meta at /home/xh/.julia/packages/GeometricFlux/u3Wfx/src/layers/meta.jl:3_

Could you give me some hints? Thank you!

(@v1.4) pkg> status
Status `~/.julia/environments/v1.4/Project.toml`
  [3a865a2d] CuArrays v2.2.0
  [864edb3b] DataStructures v0.17.17
  [5789e2e9] FileIO v1.3.0
  [587475ba] Flux v0.10.4
  [7e08b658] GeometricFlux v0.5.0
  [a2cc645c] GraphPlot v0.4.2
  [033835bb] JLD2 v0.1.13
  [093fc24a] LightGraphs v1.3.3
  [2f01184e] SparseArrays
  [10745b16] Statistics

XH

**Comment by ilancoulon** [comment]
Indeed, there is an issue that should be fixed by #45 😃

**Comment by yuehhua** [comment]
Check new version here: https://github.com/FluxML/GeometricFlux.jl/blob/master/examples/gat.jl
