### ISSUE TITLE
Edge features in GCNConv layer

### ISSUE THREAD

**Issue by tdfalc1** [FluxML/GeometricFlux.jl#77]
The FeaturedGraph type permits edge features as well as node features, however Im not too sure how these are then incorporated in the GCNConv layer. Also, what is the recommended structured of the edge features, im assuming a similar structure to a weighted adjacency matrix, but wondering if this is limited to a 1 dimensional feature for each edge, or if a 3 dimension tensor/ channel structure is permitted for multiple edge features?

```julia
function (g::GCNConv)(fg::FeaturedGraph)
    X = node_feature(fg)
    A = adjacency_matrix(fg)
    g.fg isa NullGraph || (g.fg.graph[] = A)
    L = normalized_laplacian(A, eltype(X); selfloop=true)
    X_ = g.σ.(g.weight * X * L .+ g.bias)
    FeaturedGraph(A, X_)
end
```

**Comment by yuehhua** [comment]
Thank you for the question. First of all, `GCNConv` layer is defined for feature on node, not for edge features. You may want to check the [original paper](https://arxiv.org/abs/1609.02907).
You may find some graph convolutional layers for edge features from papers but not currently GeometricFlux. Or you can also implement your own graph convolutional layer for node feature and edge feature simultaneously. If your edge features are simple, I suggest you to put it as edge weights.
For high-dimensional features, you could reshape it into a 1-dim feature and optionally reshape it back after going through the model. The computation will be the same. It is currently hard to handle high-dimensional features in GeometricFlux.

**Comment by yuehhua** [comment]
If you have any suggestions, it's welcome to reopen the issue.
